### ISSUE TITLE
페이스북 로그인 시 잘못된 페이지?

### ISSUE THREAD

**Issue by yangwansu** [javajigi/slipp#130]
로그인 하지 않은 상태에서 특정 덧글에 좋아요(별표) 를 누른 후 별표가 카운트 되지 않는 걸 목도 하고 로그인을 해야겠다하고 페이스북 로그인을 했을 때 

http://www.slipp.net/questions/168/answers/760/like#_=_ 

위와 같은 url 과 화면에는 1이라는 숫자가 달랑 나오더군요... 
다시 refresh  를 하면 정상적으로 로그인이 된걸로 나옵니다.

**Comment by javajigi** [comment]
로그인 사용자에 한해 좋아요/싫어요를 할 수 있도록 수정해 문제 해결함.
