### ISSUE TITLE
글(쓰레드) 작성시, 연관태그가 오직 하나만 달립니다.

### ISSUE THREAD

**Issue by jwChung** [javajigi/slipp#153]
제가 [질문 글](http://www.slipp.net/questions/199)을 작성하면서 
maven과 android 두 개의 연관태그들 달고 싶었는데

어떻게 작성해도 하나 maven만 달립니다.

- maven, android
- maven , android
- maven android

OS: windows 8
브라우져: 크롬(Version 30.0.1599.69 m) 
IE(v10.x.x)에서도 같은 현상이었습니다.

**Comment by javajigi** [comment]
정말 힘들고 긴 여정이었다.
한 번에 여러 가지 업데이트는 하지 말자.
기능 업데이트하면서 라이브러리 업데이트까지 하려니.. 그래도 끝내 성공은 했다.
