### ISSUE TITLE
언급하기가 보이지 않아요.

### ISSUE THREAD

**Issue by javajigi** [javajigi/slipp#180]
댓글에 언급하기가 사라졌다.
함 확인해 주라.
지난 번 배포하면서 사라진 듯하다.

**Comment by hukoru** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

hukoru@naver.com 님께 보내신 메일 <Re: [slipp] 언급하기가 보이지 않아요. (#180)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
