### ISSUE TITLE
초급자 build시 어려움에 대한 내용, 공유드립니다.

### ISSUE THREAD

**Issue by YoonSung** [javajigi/slipp#195]
> 항상 slipp.net에서 질문도 하고, 올라오는 article도 보면서 여러가지를 배우는데,
> 이렇게 사이트 소스코드까지 공개해주셔서 너무 감사드립니다~
> 예전부터 pull받아놓고 코드를 조금씩 참고했는데,
> build해서 찬찬히 보고 싶은 마음에 설정하다보니 어려움이 있어서 이렇게 이슈등록합니다.
> 바쁘시겠지만, 수정해주신다면 저같은 초급자들이 쉽게 코드를 실행할 수 있을것 같아요 :+1: 

####### 1. README.md 의 settings.xml에 대한 설정에 driverClassName이 빠져있습니다.
```
<entry key="database.driverClassName">com.mysql.jdbc.Driver</entry>
```

####### 2. src/main/resources 디렉토리에 temp-application-properties.xml 파일이 없습니다. 하나하나 에러로그를 보면서 나름대로 추합했는데, 혹시 도움될까 싶어 같이 남깁니다.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
	<comment>application-properties</comment>

	<!-- net.slipp.service.qna.FacebookService.java -->
	<entry key="facebook.application.url">test</entry>

	<!-- slipp-servlet.xml -->
	<entry key="application.url">test</entry>
	<entry key="resources.cache.seconds">300</entry>


	<!-- applicationContext-social.xml -->
	<entry key="facebook.clientId">test</entry>
	<entry key="facebook.clientSecret">test</entry>
	<entry key="twitter.consumerKey">test</entry>
	<entry key="twitter.consumerSecret">test</entry>
	<entry key="google.clientId">test</entry>
	<entry key="google.clientSecret">test</entry>
	
	
	
	<!-- applicationContext.xml -->
	<entry key="slipp.remember.token.key">test</entry>
	<entry key="slipp.remember.token.key">test</entry>
	
	
	
	<!-- infrastructure.xml -->
	<entry key="wiki.database.url">jdbc:mysql://127.0.0.1/slipp?uniCode=true&amp;characterEncoding=utf8</entry>
	<entry key="wiki.database.username">root</entry>
	<entry key="wiki.database.password"></entry>
	<entry key="wiki.database.driverClassName">com.mysql.jdbc.Driver</entry>
	<entry key="mail.server.host">test</entry>
	<entry key="mail.server.port">12312</entry>
	<entry key="mail.server.username">test</entry>
	<entry key="mail.server.password">test</entry>
</properties>
```

위 소스를 resource-development에 application-properties.xml로 등록한 후 빐드하면, 잘 작동합니다.

####### 3. jetty를 사용하시는데, 이것에 대한 언급을 한줄만 해주시면 좋을 것 같습니다. (저같은 초보를 위해!! 초보만세!)
```
mvn run jetty:run-war
```

####### 4. pom.xml의 dependency중 spring-social-google:1.0.0.M1 은 더이상 참조가 되지 않아보입니다. 릴리즈 버전을 사용하니까 정상작동하구요
```
		<dependency>
			<groupId>org.springframework.social</groupId>
			<artifactId>spring-social-google</artifactId>
			<version>1.0.0.RELEASE</version>
		</dependency>
```

아참, 위키텍스트를 extern repository에서 받아올 수 없을까 찾다보니, 같은 패키지이름으로 같은 패키지 소스코드로 보이는 org.fusesource.wikitext 도 있던데, 이건 WikiTextParserTest 에서 에러가 발생하더라구요 ^^

####### 5. SummaryServiceTest.java
107라인 
```
assertThat(siteSummary.getTitle(), is("Sublime Text 2 유용한 기능과 단축키 정리 - WindTale"));
```
블로그에 들어가보니 article제목이 바뀌어서 에러가 발생하고 있습니다.
expected 데이터값에 숫자 2를 빼야될것 같네요.

> 여러가지로 지금도 많이 배웠고, 앞으로도 slipp프로젝트에서 학습할 수 있는점이 너무 많더군요ㅎ
> 다시한번 감사말씀드리고~ 곧 다가오는 새해에 복 많이 받으시길 바래요!

**Comment by arkist** [comment]
:+1:

**Comment by javajigi** [comment]
@YoonSung 대박 고맙다.
내가 바쁘다는 핑계로 소홀히 하고 있었는데 소스 코드의 부족한 부분을 많이 채웠네.
네 의견 반영해서 수정할께.

**Comment by javajigi** [comment]
master 브랜치의 README.md 파일에 적용함.
