### ISSUE TITLE
실 서버 환경을 jdk6에서 jdk8로 업그레이드한다.

### ISSUE THREAD

**Issue by javajigi** [javajigi/slipp#199]
현재 jdk6 버전. 지난 번 jdk7으로 버전업 하다가 위키 UI가 깨지는 현상이 발생해 원복함.

이번 기회에 jdk8로 업그레이드 시도해 본다.

**Comment by arkist** [comment]
:+1:

**Comment by javajigi** [comment]
d2의 도움을 받아 서버 이전하고 jdk 버전을 1.8로 업그레이드 진행함.
