### ISSUE TITLE
slipp 서비스에 d2 배너 추가한다.

### ISSUE THREAD

**Issue by javajigi** [javajigi/slipp#213]

**Comment by javajigi** [comment]
@arkist 이번에 slipp 서버를 d2에서 지원받는 것으로 결정하고 서비스 이전했다.
이에 따라 배너 광고를 달아줘야 해서 배너를 추가했다.

소스 코드는 https://github.com/javajigi/slipp/blob/develop/webapp/WEB-INF/jsp/index.jsp 의 98에서 101 사이보면 있다. 

네가 확인하고 위치나 css 수정이 필요하면 수정 요청한다.

**Comment by arkist** [comment]
@javajigi rss를 빼고 '지원' 항목으로 d2와 아틀라시안이 추가되는건가요?
소스코드를 조금 손보려고 하는데 로컬 개발환경을 다시 구성하려다 보니 README에 있는 내용으로는 진행이 안되는것 같습니다. (deploy-lib.sh이 없는 등..) 문서의 보완이나 설명 부탁드려요~

**Comment by javajigi** [comment]
@arkist 
맞다. 기존에 있던 rss를 제거했다. 활용도도 낮고 해서..

문서는 보완할께. 얼마전에 위키 문법을 markdown으로 변경하면서 기존에 사용하던 라이브러리가 필요없어져서 deploy-lib.sh를 제거했다. 그리고 java 버전을 1.8로 업그레이드했다. 로컬에 jdk 버전이 낮으면 문제가 될 수 있다. jdk 버전 낮으면 1.8로 다시 설치해 봐라.

thx.

**Comment by javajigi** [comment]
@arkist 
문서 수정해서 올렸으니 다시 한번 시도해 봐라.
혹시 그래도 안되면 댓글 남겨주라.
