### ISSUE TITLE
댓글 가져오기 문제

### ISSUE THREAD

**Issue by arkist** [javajigi/slipp#217]
![2015-05-07 3 11 49](https://cloud.githubusercontent.com/assets/1099068/7509433/6ab01e0c-f4cb-11e4-8fe8-78db236d0d96.png)

글목록에는 댓글이 추가된걸로 보이는데 [본문](http://slipp.net/questions/101)을 보면 해당 댓글을 확인할 수 없습니다.
아마 sns에서 댓글을 가져오는데 문제가 있는걸로 보여집니다.

**Comment by javajigi** [comment]
@arkist 
이 경우는 댓글을 썼다가 지우는 경우 발생한다.
댓글을 쓸 때 최신 정보를 업데이트 하는데 삭제할 경우 다시 원복하지 않는 버그다. 원인은 알고 있으니 해결할께
