### ISSUE TITLE
페이스북 로그인이 안됨

### ISSUE THREAD

**Issue by arkist** [javajigi/slipp#222]
404 페이지로 보냅니다

**Comment by javajigi** [comment]
@arkist 얼마 전에 페이스북 api가 변경되어 수정했는데 아직도 문제있는 사용자가 있나보다.
나는 정상적으로 로그인되고 있어 재현하기 힘들다.

다음 과정 테스트 부탁
* 로그아웃 후 재로그인 요청
* 404 에러 후에 url을 http://www.slipp.net으로 변경하고 로그인 상태 유무
  * NEXT 학생 중 정상적으로 접근된다는 경우가 있어서..

**Comment by arkist** [comment]
@javajigi 
로그인이 안되서 로그아웃을 할 수 없습니다 :crying_cat_face: 
404에러페이지 url은 http://www.slipp.net/signin?error=provider#_=_ 입니다. 
`[POST] /signin/facebook` 처리가 안되고 있어요
