### ISSUE TITLE
태그 목록 중 angular.js와 node.js가 각 1개 글 목록이 있는데 클릭 시 실제 글이 보이지 않습니다.

### ISSUE THREAD

**Issue by hwiba** [javajigi/slipp#229]
![2015-08-17 12 33 43](https://cloud.githubusercontent.com/assets/11264492/9297561/686d8aa6-44dc-11e5-9930-eaa2effe4f3a.png)

**Comment by javajigi** [comment]
버그 신고 고맙다.
이 놈은 태그가 아니라 javascript 파일로 인식하는 것으로 추정된다.
수정 작업 들어가야겠다.
