### ISSUE TITLE
페이스북 로그인을 시도중에 에러페이지가 뜹니다

### ISSUE THREAD

**Issue by BongGyun** [javajigi/slipp#230]
![image](https://cloud.githubusercontent.com/assets/15025169/11234872/6faeebda-8e0f-11e5-829c-1fa1b7b42307.png)

ㅠㅠ

**Comment by arkist** [comment]
`1boon` <-ㅋㅋ

**Comment by BongGyun** [comment]
ㅋㅋㅋ
https://github.com/javajigi/slipp/issues/222 이미 있는 이슈였네요...

**Comment by javajigi** [comment]
@BongGyun 
제보 감사합니다.
이 이슈를 재현하기 힘들어 계속 묵혀두고 있는 상황이네요.

**Comment by javajigi** [comment]
중복 이슈라  close 합니다.
