### ISSUE TITLE
태그 삭제 버튼이 노출됩니다.

### ISSUE THREAD

**Issue by yjw2288** [javajigi/slipp#269]
제가 작성한 글이 아닌데 태그 삭제, 태그 등록이 됩니다.

![image](https://user-images.githubusercontent.com/1639209/33971940-825f6cf6-e0be-11e7-81f6-eba79a2174d3.png)

**Comment by javajigi** [comment]
태그는 아무나 추가하고 삭제하는 것으로 생각하고 구현했다.
자신의 글에 대해서만 추가/삭제가 아님.

**Comment by javajigi** [comment]
@yjw2288 slipp 개발에 관심이 많으면 내년에 개편 프로젝트할 때 같이 해볼까? ㅋㅋ

**Comment by yjw2288** [comment]
개편 프로젝트있다는 이야기는 @arkist 진우형에게 들었습니다 ㅋㅋ
한번 개편해보는 것도 재미있을 거 같네요 ㅎㅎ
이 이슈가 스펙이라면 클로즈 할께요
